version: '3'

services:

    php:
        build:
          context: .
          dockerfile: Dockerfile
        container_name: 'php'
        ports:
            - "9000:9000"
        volumes:
            - ./:/app
        working_dir: /app
        networks:
            - app-network

    nginx:
        image: nginx
        container_name: 'nginx'
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/app
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

    db:
        image: mysql:5.7.22
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: password
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - dbdata:/var/lib/mysql/
            - dump:/app/dump
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    dump:
    dbdata:
        driver: local
