version: '3'

services:

    php:
        build: docker
        container_name: 'php'
        ports:
            - "9000:9000"
        volumes:
            - ./:/app
        working_dir: /app

    nginx:
        image: nginx
        container_name: 'nginx'
        restart: always
        working_dir: /app
        ports:
            - '7055:80'
        volumes:
            - ./:/app
            - ./docker/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf

    db:
        image: mysql:5.7.22
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: password
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - dbdata:/var/lib/mysql/
            - ./mysql/my.cnf:/etc/mysql/my.cnf

    supervisor:
        build: docker/supervisor
        container_name: 'supervisor'
        volumes:
            - ./:/app
            - ./docker/supervisor/supervisord.conf:/etc/supervisor/supervisord.conf
        working_dir: /app
        command: ["supervisord", "-c", "/etc/supervisor/supervisord.conf"]

volumes:
  dbdata:
    driver: local
